### ISSUE TITLE
index_key is required when lifecycle.drop = true

### ISSUE THREAD

**Issue by brantburnett** [brantburnett/couchbase-index-manager#67]
Triggering YAML:
```yaml
index_key:
- type
- id
name: example
num_replica: 0
---
index_key:
- type
- name
name: example2
num_replica: 0
---
lifecycle:
  drop: true
name: example3
```

Error message:
```
Error: index_key must include at least one key in example
```
